before_script:
  - ruby -v
  - which ruby

stages:
  - init
  - test
  - deploy

init_job:
  stage: init
  script:
    - sudo apt-get install thrift-compiler
    - gem install bundler --no-ri --no-rdoc
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec_job:
  stage: test
  script:
    - bundle exec rspec

deploy_job:
  stage: deploy
  script:
    - bundle exec rake build
 
